/*
 * Copyright (C) 2019 Rodrigo Ferreira Rodrigues <Email: rodrigo2208@gmail.com GitHub: https://github.com/rfrodriguespe>
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package br.com.monetae.view;

import br.com.monetae.control.CaixaThread;
import br.com.monetae.control.ClienteControl;
import br.com.monetae.control.ThreadBarra;
import br.com.monetae.model.Cliente;
import br.com.monetae.utils.EnviarEmail;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.GregorianCalendar;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.Timer;

/**
 *
 * @author Rodrigo Ferreira Rodrigues
 * <Email: rodrigo2208@gmail.com GitHub: https://github.com/rfrodriguespe>
 */
public class TelaAtendimento extends javax.swing.JInternalFrame {

    //LOG
    private static final String BARRA = System.getProperty("file.separator");
    private static final String PASTA_USUARIO = System.getProperty("user.home");
    private static final String BASE_LOGS = PASTA_USUARIO + BARRA + "monetae";
    private static final String ARQUIVO_LOG = BASE_LOGS + BARRA + "monetae-log.txt";
    //LOG

    public static ArrayList<Cliente> listaDeClientesGerados = new ArrayList<>();
    public static ArrayList<Cliente> listaDeAtendidos = new ArrayList<>();
    public static ThreadBarra tb;

    private Timer timer;
    public static int currentSegundo = 0;
    public static int currentMinuto = 0;
    public static int currentHora = 0;
    private int velocidade = 1000;

    public static CaixaThread CxT01;
    public static CaixaThread CxT02;
    public static CaixaThread CxT03;
    public static CaixaThread CxT04;
    public static CaixaThread CxT05;
    public static CaixaThread CxT06;
    public static CaixaThread CxT07;
    public static CaixaThread CxT08;

    /**
     * Creates new form TelaAtendimento
     */
    public TelaAtendimento() {
        initComponents();
        iniciarContagem();
        timer.stop();
        // Adiciona rodapé com a data e hora atuais
        String cabecalhoLog = "Monetae Câmbio - Log de eventos\n";
        String inicioLog = "" + new SimpleDateFormat("[dd'/'MM'/'yyyy - HH:mm:ss]").format(GregorianCalendar.getInstance().getTime());
        logDoPrograma.append(cabecalhoLog);
        logDoPrograma.append(inicioLog + " Tela de atendimento aberta\n");
        jLabelLocalDoLog.setText(BASE_LOGS);
        //
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPaneAtendimento = new javax.swing.JTabbedPane();
        jPanelAtendimento = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        labelClientesGerados = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        labelClientesAtendidos = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabelCaixa1 = new javax.swing.JLabel();
        jLabelTempoClienteDaVezCx1 = new javax.swing.JLabel();
        barraProgressoCx1 = new javax.swing.JProgressBar();
        jLabel8 = new javax.swing.JLabel();
        barraProgressoCx2 = new javax.swing.JProgressBar();
        jLabelTempoClienteDaVezCx2 = new javax.swing.JLabel();
        jLabelCaixa2 = new javax.swing.JLabel();
        jPanelControleCronometro = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jLabelCronometro = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        btnAtendimentoSair = new javax.swing.JButton();
        jLabelLogo = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        barraProgressoCx3 = new javax.swing.JProgressBar();
        jLabel9 = new javax.swing.JLabel();
        barraProgressoCx4 = new javax.swing.JProgressBar();
        jLabelTempoClienteDaVezCx3 = new javax.swing.JLabel();
        jLabelTempoClienteDaVezCx4 = new javax.swing.JLabel();
        jLabelCaixa3 = new javax.swing.JLabel();
        jLabelCaixa4 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        barraProgressoCx5 = new javax.swing.JProgressBar();
        jLabel15 = new javax.swing.JLabel();
        barraProgressoCx6 = new javax.swing.JProgressBar();
        jLabel16 = new javax.swing.JLabel();
        barraProgressoCx7 = new javax.swing.JProgressBar();
        jLabel17 = new javax.swing.JLabel();
        barraProgressoCx8 = new javax.swing.JProgressBar();
        jLabelTempoClienteDaVezCx5 = new javax.swing.JLabel();
        jLabelTempoClienteDaVezCx6 = new javax.swing.JLabel();
        jLabelTempoClienteDaVezCx7 = new javax.swing.JLabel();
        jLabelTempoClienteDaVezCx8 = new javax.swing.JLabel();
        jLabelCaixa5 = new javax.swing.JLabel();
        jLabelCaixa6 = new javax.swing.JLabel();
        jLabelCaixa7 = new javax.swing.JLabel();
        jLabelCaixa8 = new javax.swing.JLabel();
        jPanelLog = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        logDoPrograma = new javax.swing.JTextArea();
        jButton9 = new javax.swing.JButton();
        jLabelLocalDoLog = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabelLogo1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabelLogo2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabelTotalClientesAtendidos = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabelCompraMoeda = new javax.swing.JLabel();
        jLabelVendaMoeda = new javax.swing.JLabel();
        jLabelRecRemessa = new javax.swing.JLabel();
        jLabelEnvioRemessa = new javax.swing.JLabel();
        jLabelSwift = new javax.swing.JLabel();
        jLabelSeguro = new javax.swing.JLabel();
        jButton8 = new javax.swing.JButton();

        setClosable(true);
        setMaximizable(true);
        setTitle("Monetae - Atendimento");
        setToolTipText("");

        jLabel2.setText("Clientes na loja:");

        labelClientesGerados.setText("0");

        jButton1.setText("Abrir Loja");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel3.setText("Clientes atendidos até o momento:");

        labelClientesAtendidos.setText("0");

        jLabel1.setText("Caixa 01:");

        jLabel4.setText("Tempo de AT");

        jLabel5.setText("Cliente em atendimento");

        jLabelCaixa1.setText("xxx");

        jLabelTempoClienteDaVezCx1.setText("0000");

        barraProgressoCx1.setStringPainted(true);

        jLabel8.setText("Caixa 02:");

        barraProgressoCx2.setStringPainted(true);

        jLabelTempoClienteDaVezCx2.setText("0000");

        jLabelCaixa2.setText("xxx");

        jPanelControleCronometro.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jButton4.setText("Pause");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("Play");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText("Stop");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jLabelCronometro.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        jLabelCronometro.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCronometro.setText("00:00:00");
        jLabelCronometro.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout jPanelControleCronometroLayout = new javax.swing.GroupLayout(jPanelControleCronometro);
        jPanelControleCronometro.setLayout(jPanelControleCronometroLayout);
        jPanelControleCronometroLayout.setHorizontalGroup(
            jPanelControleCronometroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelControleCronometroLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelControleCronometroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelControleCronometroLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jButton5)
                        .addGap(18, 18, 18)
                        .addComponent(jButton4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton6))
                    .addComponent(jLabelCronometro, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        jPanelControleCronometroLayout.setVerticalGroup(
            jPanelControleCronometroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelControleCronometroLayout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(jLabelCronometro, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelControleCronometroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4)
                    .addComponent(jButton5)
                    .addComponent(jButton6))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jButton3.setText("Iniciar os atendimento");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        btnAtendimentoSair.setText("Fechar Janela");
        btnAtendimentoSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtendimentoSairActionPerformed(evt);
            }
        });

        jLabelLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/monetae/imagens/logo.png"))); // NOI18N

        jLabel6.setText("Caixa 03:");

        barraProgressoCx3.setStringPainted(true);

        jLabel9.setText("Caixa 04:");

        barraProgressoCx4.setStringPainted(true);

        jLabelTempoClienteDaVezCx3.setText("0000");

        jLabelTempoClienteDaVezCx4.setText("0000");

        jLabelCaixa3.setText("xxx");

        jLabelCaixa4.setText("xxx");

        jLabel14.setText("Caixa 05:");

        barraProgressoCx5.setStringPainted(true);

        jLabel15.setText("Caixa 06:");

        barraProgressoCx6.setStringPainted(true);

        jLabel16.setText("Caixa 07:");

        barraProgressoCx7.setStringPainted(true);

        jLabel17.setText("Caixa 08:");

        barraProgressoCx8.setStringPainted(true);

        jLabelTempoClienteDaVezCx5.setText("0000");

        jLabelTempoClienteDaVezCx6.setText("0000");

        jLabelTempoClienteDaVezCx7.setText("0000");

        jLabelTempoClienteDaVezCx8.setText("0000");

        jLabelCaixa5.setText("xxx");

        jLabelCaixa6.setText("xxx");

        jLabelCaixa7.setText("xxx");

        jLabelCaixa8.setText("xxx");

        javax.swing.GroupLayout jPanelAtendimentoLayout = new javax.swing.GroupLayout(jPanelAtendimento);
        jPanelAtendimento.setLayout(jPanelAtendimentoLayout);
        jPanelAtendimentoLayout.setHorizontalGroup(
            jPanelAtendimentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAtendimentoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelAtendimentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelAtendimentoLayout.createSequentialGroup()
                        .addGroup(jPanelAtendimentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel6)
                            .addGroup(jPanelAtendimentoLayout.createSequentialGroup()
                                .addGroup(jPanelAtendimentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanelAtendimentoLayout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addGap(271, 271, 271)
                                        .addComponent(jLabel4))
                                    .addGroup(jPanelAtendimentoLayout.createSequentialGroup()
                                        .addComponent(barraProgressoCx1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabelTempoClienteDaVezCx1))
                                    .addGroup(jPanelAtendimentoLayout.createSequentialGroup()
                                        .addComponent(barraProgressoCx2, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabelTempoClienteDaVezCx2)))
                                .addGap(18, 18, 18)
                                .addGroup(jPanelAtendimentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanelAtendimentoLayout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jButton1))
                                    .addGroup(jPanelAtendimentoLayout.createSequentialGroup()
                                        .addGroup(jPanelAtendimentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanelAtendimentoLayout.createSequentialGroup()
                                                .addComponent(jLabelCaixa2)
                                                .addGap(176, 176, 176)
                                                .addComponent(jPanelControleCronometro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(jLabelCaixa1))
                                        .addGap(0, 0, Short.MAX_VALUE)))))
                        .addGap(169, 169, 169))
                    .addGroup(jPanelAtendimentoLayout.createSequentialGroup()
                        .addGroup(jPanelAtendimentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14)
                            .addComponent(jLabel17)
                            .addGroup(jPanelAtendimentoLayout.createSequentialGroup()
                                .addComponent(barraProgressoCx8, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabelTempoClienteDaVezCx8))
                            .addGroup(jPanelAtendimentoLayout.createSequentialGroup()
                                .addComponent(barraProgressoCx3, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(jPanelAtendimentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanelAtendimentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabelTempoClienteDaVezCx5, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanelAtendimentoLayout.createSequentialGroup()
                                            .addComponent(jLabelTempoClienteDaVezCx4)
                                            .addGap(83, 83, 83)))
                                    .addGroup(jPanelAtendimentoLayout.createSequentialGroup()
                                        .addComponent(jLabelTempoClienteDaVezCx3)
                                        .addGap(56, 56, 56)
                                        .addGroup(jPanelAtendimentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabelCaixa4)
                                            .addComponent(jLabelCaixa3)
                                            .addComponent(jLabelCaixa5)
                                            .addComponent(jLabelCaixa6)
                                            .addComponent(jLabelCaixa7)
                                            .addComponent(jLabelCaixa8))))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanelAtendimentoLayout.createSequentialGroup()
                        .addGroup(jPanelAtendimentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelAtendimentoLayout.createSequentialGroup()
                                .addGroup(jPanelAtendimentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addComponent(barraProgressoCx4, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(barraProgressoCx5, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel15)
                                    .addComponent(barraProgressoCx6, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(barraProgressoCx7, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel16))
                                .addGap(18, 18, 18)
                                .addGroup(jPanelAtendimentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelTempoClienteDaVezCx7)
                                    .addComponent(jLabelTempoClienteDaVezCx6)))
                            .addGroup(jPanelAtendimentoLayout.createSequentialGroup()
                                .addGap(592, 592, 592)
                                .addGroup(jPanelAtendimentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanelAtendimentoLayout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(labelClientesAtendidos, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanelAtendimentoLayout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(labelClientesGerados, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addContainerGap(330, Short.MAX_VALUE))
                    .addGroup(jPanelAtendimentoLayout.createSequentialGroup()
                        .addComponent(btnAtendimentoSair)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabelLogo))))
        );
        jPanelAtendimentoLayout.setVerticalGroup(
            jPanelAtendimentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAtendimentoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelAtendimentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel2)
                    .addComponent(labelClientesGerados)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelAtendimentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(barraProgressoCx1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelTempoClienteDaVezCx1)
                    .addComponent(jLabelCaixa1)
                    .addComponent(jLabel3)
                    .addComponent(labelClientesAtendidos))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelAtendimentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelAtendimentoLayout.createSequentialGroup()
                        .addGroup(jPanelAtendimentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(barraProgressoCx2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelTempoClienteDaVezCx2)
                            .addComponent(jLabelCaixa2))
                        .addGap(5, 5, 5)
                        .addComponent(jLabel6)
                        .addGap(9, 9, 9)
                        .addGroup(jPanelAtendimentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(barraProgressoCx3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelTempoClienteDaVezCx3)
                            .addComponent(jLabelCaixa3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelAtendimentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(barraProgressoCx4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelTempoClienteDaVezCx4)
                            .addComponent(jLabelCaixa4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelAtendimentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(barraProgressoCx5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelTempoClienteDaVezCx5)
                            .addComponent(jLabelCaixa5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelAtendimentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(barraProgressoCx6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelTempoClienteDaVezCx6)
                            .addComponent(jLabelCaixa6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelAtendimentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(barraProgressoCx7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelTempoClienteDaVezCx7)
                            .addComponent(jLabelCaixa7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel17)
                        .addGap(5, 5, 5)
                        .addGroup(jPanelAtendimentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(barraProgressoCx8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelTempoClienteDaVezCx8)
                            .addComponent(jLabelCaixa8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 218, Short.MAX_VALUE)
                        .addGroup(jPanelAtendimentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnAtendimentoSair)
                            .addComponent(jButton3))
                        .addContainerGap())
                    .addGroup(jPanelAtendimentoLayout.createSequentialGroup()
                        .addComponent(jPanelControleCronometro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabelLogo))))
        );

        jTabbedPaneAtendimento.addTab("Atendimento", jPanelAtendimento);

        logDoPrograma.setColumns(20);
        logDoPrograma.setRows(5);
        jScrollPane1.setViewportView(logDoPrograma);

        jButton9.setText("Salvar Log");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jLabelLocalDoLog.setText("c:\\");

            jLabel13.setText("Local de Armazenamento do Arquivo:");

            jLabelLogo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/monetae/imagens/logo.png"))); // NOI18N

            javax.swing.GroupLayout jPanelLogLayout = new javax.swing.GroupLayout(jPanelLog);
            jPanelLog.setLayout(jPanelLogLayout);
            jPanelLogLayout.setHorizontalGroup(
                jPanelLogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jScrollPane1)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelLogLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jButton9)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jLabel13)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jLabelLocalDoLog)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 539, Short.MAX_VALUE)
                    .addComponent(jLabelLogo1)
                    .addContainerGap())
            );
            jPanelLogLayout.setVerticalGroup(
                jPanelLogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelLogLayout.createSequentialGroup()
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 437, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 83, Short.MAX_VALUE)
                    .addGroup(jPanelLogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabelLogo1)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelLogLayout.createSequentialGroup()
                            .addGroup(jPanelLogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jButton9)
                                .addComponent(jLabel13)
                                .addComponent(jLabelLocalDoLog))
                            .addContainerGap())))
            );

            jTabbedPaneAtendimento.addTab("Logs", jPanelLog);

            jLabelLogo2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/monetae/imagens/logo.png"))); // NOI18N

            jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Estatísticas"));

            jLabel10.setText("Total de Clientes atendidos: ");

            jLabelTotalClientesAtendidos.setText("0");

            jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/monetae/imagens/iconEmail24x24.png"))); // NOI18N
            jButton2.setText("Enviar Email");
            jButton2.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButton2ActionPerformed(evt);
                }
            });

            jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/monetae/imagens/iconePdf24x24.png"))); // NOI18N
            jButton7.setText("Gerar PDF");
            jButton7.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButton7ActionPerformed(evt);
                }
            });

            jLabel11.setText("Compra de Moeda:");

            jLabel12.setText("Venda de Moeda:");

            jLabel18.setText("Recebimento de Remessa:");

            jLabel19.setText("Envio de Remessa:");

            jLabel20.setText("Swift:");

            jLabel21.setText("Seguro Viagem:");

            jLabelCompraMoeda.setText("0");

            jLabelVendaMoeda.setText("0");

            jLabelRecRemessa.setText("0");

            jLabelEnvioRemessa.setText("0");

            jLabelSwift.setText("0");

            jLabelSeguro.setText("0");

            jButton8.setText("Reseta Dados");
            jButton8.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButton8ActionPerformed(evt);
                }
            });

            javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
            jPanel2.setLayout(jPanel2Layout);
            jPanel2Layout.setHorizontalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGap(29, 29, 29)
                            .addComponent(jButton2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jButton7))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel10)
                                .addComponent(jLabel11)
                                .addComponent(jLabel12)
                                .addComponent(jLabel18)
                                .addComponent(jLabel19)
                                .addComponent(jLabel20)
                                .addComponent(jLabel21))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabelRecRemessa)
                                        .addComponent(jLabelEnvioRemessa))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                                    .addComponent(jButton8))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabelCompraMoeda)
                                        .addComponent(jLabelTotalClientesAtendidos)
                                        .addComponent(jLabelVendaMoeda)
                                        .addComponent(jLabelSwift)
                                        .addComponent(jLabelSeguro))
                                    .addGap(0, 0, Short.MAX_VALUE)))))
                    .addContainerGap())
            );
            jPanel2Layout.setVerticalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel10)
                        .addComponent(jLabelTotalClientesAtendidos))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel11)
                        .addComponent(jLabelCompraMoeda))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel12)
                        .addComponent(jLabelVendaMoeda))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel18)
                                .addComponent(jLabelRecRemessa))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel19)
                                .addComponent(jLabelEnvioRemessa)))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGap(13, 13, 13)
                            .addComponent(jButton8)))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel20)
                        .addComponent(jLabelSwift))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel21)
                        .addComponent(jLabelSeguro))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton2)
                        .addComponent(jButton7))
                    .addContainerGap())
            );

            javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
            jPanel1.setLayout(jPanel1Layout);
            jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabelLogo2))
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(55, 55, 55)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(781, Short.MAX_VALUE))
            );
            jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addGap(31, 31, 31)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 258, Short.MAX_VALUE)
                    .addComponent(jLabelLogo2))
            );

            jTabbedPaneAtendimento.addTab("Relatórios", jPanel1);

            javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
            getContentPane().setLayout(layout);
            layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jTabbedPaneAtendimento, javax.swing.GroupLayout.PREFERRED_SIZE, 1164, javax.swing.GroupLayout.PREFERRED_SIZE)
            );
            layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jTabbedPaneAtendimento, javax.swing.GroupLayout.PREFERRED_SIZE, 639, javax.swing.GroupLayout.PREFERRED_SIZE)
            );

            setBounds(0, 0, 1180, 669);
        }// </editor-fold>//GEN-END:initComponents

    private void btnAtendimentoSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtendimentoSairActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnAtendimentoSairActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        ClienteControl.geraCliente(20);
        labelClientesGerados.setText(""+listaDeClientesGerados.size());
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        timer.stop();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        timer.restart();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        stopTime();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        timer.restart();
        try {
            CxT01 = new CaixaThread("01", barraProgressoCx1, jLabelCaixa1, jLabelTempoClienteDaVezCx1,  logDoPrograma);
            Thread.sleep(100);
            CxT02 = new CaixaThread("02", barraProgressoCx2, jLabelCaixa2, jLabelTempoClienteDaVezCx2,  logDoPrograma);
            Thread.sleep(100);
            CxT03 = new CaixaThread("03", barraProgressoCx3, jLabelCaixa3, jLabelTempoClienteDaVezCx3,  logDoPrograma);
            Thread.sleep(100);
            CxT04 = new CaixaThread("04", barraProgressoCx4, jLabelCaixa4, jLabelTempoClienteDaVezCx4,  logDoPrograma);
            Thread.sleep(100);
            CxT05 = new CaixaThread("05", barraProgressoCx5, jLabelCaixa5, jLabelTempoClienteDaVezCx5,  logDoPrograma);
            Thread.sleep(100);
            CxT06 = new CaixaThread("06", barraProgressoCx6, jLabelCaixa6, jLabelTempoClienteDaVezCx6,  logDoPrograma);
            Thread.sleep(100);
            CxT07 = new CaixaThread("07", barraProgressoCx7, jLabelCaixa7, jLabelTempoClienteDaVezCx7,  logDoPrograma);
            Thread.sleep(100);
            CxT08 = new CaixaThread("08", barraProgressoCx8, jLabelCaixa8, jLabelTempoClienteDaVezCx8,  logDoPrograma);
            
        } catch (InterruptedException ex) {
            Logger.getLogger(TelaAtendimento.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:

        
        //VERIFICA CAMINHO DA PASTA
        File pastaLogs = new File(BASE_LOGS);
        if (!pastaLogs.exists()) {
            pastaLogs.mkdirs();
        }
        //VERIFICA CAMINHO DA PASTA
        
        //SALVA LOG
        File arquivoLog = new File(ARQUIVO_LOG);
        if (!arquivoLog.exists()) {
            try {
                arquivoLog.createNewFile();
            } catch (IOException ex) {
                ex.printStackTrace();
            }
        } else {
            try {
                
                //PEGANDO O CONTEUDO ATUAL DO LOG
                FileReader fr = new FileReader(arquivoLog);
                BufferedReader br = new BufferedReader(fr);
                Vector logAtual = new Vector();
                while(br.ready()){
                    logAtual.add(br.readLine());
                }
                //PEGANDO O CONTEUDO ATUAL DO LOG
                FileWriter fw = new FileWriter(arquivoLog);
                BufferedWriter bw = new BufferedWriter(fw);
                logAtual.add(logDoPrograma.getText());
                bw.write(logAtual.toString());
                bw.close();
                fw.close();
            } catch (IOException ex) {
                Logger.getLogger(TelaAtendimento.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        //SALVA LOG
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        String email = JOptionPane.showInputDialog("Digite o email");
        JOptionPane.showMessageDialog(this, "Email enviado para " + email);
        EnviarEmail.envia(email);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
//        JFileChooser relatorio = new JFileChooser();
//        relatorio.setDialogTitle("Salvar Relatório");
//        relatorio.setFileSelectionMode(JFileChooser.FILES_ONLY);
//        relatorio.setAcceptAllFileFilterUsed(false);
//        FileNameExtensionFilter filter = new FileNameExtensionFilter("Arquivo PDF", ".pdf");
//        relatorio.setFileFilter(filter);
//        int resultado = relatorio.showSaveDialog(this);
//
//        if (resultado == JFileChooser.APPROVE_OPTION) {
//            File file = relatorio.getSelectedFile();
//            if (file.exists()) {
//                int selecionaOpcao = JOptionPane.showConfirmDialog(null,
//                    " O arquivo já existe, deseja sobrescreve-lo? ", null,
//                    JOptionPane.OK_CANCEL_OPTION);
//                if (selecionaOpcao == JOptionPane.OK_OPTION) {
//                    geraPdf(file.getPath() + ".pdf");
//                } else if (selecionaOpcao == JOptionPane.CANCEL_OPTION) {
//                    JOptionPane.showMessageDialog(this, "Ação Cancelada");
//                }
//            } else {
//                geraPdf(file.getPath() + ".pdf");
//            }
//        } else if (resultado == JFileChooser.CANCEL_OPTION) {
//            JOptionPane.showMessageDialog(this, "Ação Cancelada");
//        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        //resetaEstatisticas();
        stopTime();
    }//GEN-LAST:event_jButton8ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JProgressBar barraProgressoCx1;
    public static javax.swing.JProgressBar barraProgressoCx2;
    public static javax.swing.JProgressBar barraProgressoCx3;
    public static javax.swing.JProgressBar barraProgressoCx4;
    public static javax.swing.JProgressBar barraProgressoCx5;
    public static javax.swing.JProgressBar barraProgressoCx6;
    public static javax.swing.JProgressBar barraProgressoCx7;
    public static javax.swing.JProgressBar barraProgressoCx8;
    public static javax.swing.JButton btnAtendimentoSair;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    public static javax.swing.JLabel jLabelCaixa1;
    public static javax.swing.JLabel jLabelCaixa2;
    public static javax.swing.JLabel jLabelCaixa3;
    public static javax.swing.JLabel jLabelCaixa4;
    public static javax.swing.JLabel jLabelCaixa5;
    public static javax.swing.JLabel jLabelCaixa6;
    public static javax.swing.JLabel jLabelCaixa7;
    public static javax.swing.JLabel jLabelCaixa8;
    public static javax.swing.JLabel jLabelCompraMoeda;
    public static javax.swing.JLabel jLabelCronometro;
    public static javax.swing.JLabel jLabelEnvioRemessa;
    private javax.swing.JLabel jLabelLocalDoLog;
    private javax.swing.JLabel jLabelLogo;
    private javax.swing.JLabel jLabelLogo1;
    private javax.swing.JLabel jLabelLogo2;
    public static javax.swing.JLabel jLabelRecRemessa;
    public static javax.swing.JLabel jLabelSeguro;
    public static javax.swing.JLabel jLabelSwift;
    public static javax.swing.JLabel jLabelTempoClienteDaVezCx1;
    public static javax.swing.JLabel jLabelTempoClienteDaVezCx2;
    public static javax.swing.JLabel jLabelTempoClienteDaVezCx3;
    public static javax.swing.JLabel jLabelTempoClienteDaVezCx4;
    public static javax.swing.JLabel jLabelTempoClienteDaVezCx5;
    public static javax.swing.JLabel jLabelTempoClienteDaVezCx6;
    public static javax.swing.JLabel jLabelTempoClienteDaVezCx7;
    public static javax.swing.JLabel jLabelTempoClienteDaVezCx8;
    public static javax.swing.JLabel jLabelTotalClientesAtendidos;
    public static javax.swing.JLabel jLabelVendaMoeda;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanelAtendimento;
    private javax.swing.JPanel jPanelControleCronometro;
    private javax.swing.JPanel jPanelLog;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPaneAtendimento;
    public static javax.swing.JLabel labelClientesAtendidos;
    public static javax.swing.JLabel labelClientesGerados;
    public static javax.swing.JTextArea logDoPrograma;
    // End of variables declaration//GEN-END:variables

    private void stopTime() {
        timer.stop();
        currentHora = 0;
        currentMinuto = 0;
        currentSegundo = 0;
        jLabelCronometro.setText("00:00:00");
    }

    private void iniciarContagem() {
        ActionListener action = new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                currentSegundo++;

                if (currentSegundo == 60) {
                    currentMinuto++;
                    currentSegundo = 0;
                }

                if (currentMinuto == 60) {
                    currentHora++;
                    currentMinuto = 0;
                }

                String hr = currentHora <= 9 ? "0" + currentHora : currentHora + "";
                String min = currentMinuto <= 9 ? "0" + currentMinuto : currentMinuto + "";
                String seg = currentSegundo <= 9 ? "0" + currentSegundo : currentSegundo + "";

                jLabelCronometro.setText(hr + ":" + min + ":" + seg);
            }
        };
        this.timer = new Timer(velocidade, action);
        this.timer.start();
    }

}
