/*
 * Copyright (C) 2019 Rodrigo Ferreira Rodrigues <Email: rodrigo2208@gmail.com GitHub: https://github.com/rfrodriguespe>
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package br.com.monetae.view;


import br.com.monetae.utils.Traduzir;
import java.awt.Desktop;
import java.awt.Toolkit;
import java.io.File;
import java.io.IOException;
import javax.swing.JOptionPane;
import javax.swing.plaf.basic.BasicInternalFrameUI;

/**
 *
 * @author Rodrigo Ferreira Rodrigues
 * <Email: rodrigo2208@gmail.com GitHub: https://github.com/rfrodriguespe>
 */
public class TelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/br/com/monetae/imagens/monetae-icone-91x91.png")));
        
    }
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fundoTelaPrincipal = new javax.swing.JDesktopPane();
        jLabelLogoMonetae = new javax.swing.JLabel();
        jLabelFnr = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        menuTelaPrincipal = new javax.swing.JMenuBar();
        menuInicio = new javax.swing.JMenu();
        subMenuCostumer = new javax.swing.JMenuItem();
        subMenuSair = new javax.swing.JMenuItem();
        menuSettings = new javax.swing.JMenu();
        subMenuIdioma = new javax.swing.JMenu();
        subMenuIdiomaBR = new javax.swing.JMenuItem();
        subMenuIdiomaEN = new javax.swing.JMenuItem();
        menuAbout = new javax.swing.JMenu();
        submenuSobre = new javax.swing.JMenuItem();
        submenuProjeto = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Monetae Câmbio - Gerenciamento de Atendimento (Projeto P1 - TAP)");
        setExtendedState(6);
        setMaximumSize(new java.awt.Dimension(1024, 768));
        setMinimumSize(new java.awt.Dimension(640, 480));

        fundoTelaPrincipal.setBackground(new java.awt.Color(240, 240, 240));
        fundoTelaPrincipal.setMaximumSize(new java.awt.Dimension(1920, 1080));
        fundoTelaPrincipal.setMinimumSize(new java.awt.Dimension(640, 480));

        jLabelLogoMonetae.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelLogoMonetae.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/monetae/imagens/monetae-logo.png"))); // NOI18N
        jLabelLogoMonetae.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabelFnr.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelFnr.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/monetae/imagens/logo_fnr.png"))); // NOI18N
        jLabelFnr.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("TAP - Técnicas Avançadas de Programação");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Prof: Anderson Elias");
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Aluno: Rodrigo Ferreira Rodrigues");
        jLabel3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        fundoTelaPrincipal.setLayer(jLabelLogoMonetae, javax.swing.JLayeredPane.DEFAULT_LAYER);
        fundoTelaPrincipal.setLayer(jLabelFnr, javax.swing.JLayeredPane.DEFAULT_LAYER);
        fundoTelaPrincipal.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        fundoTelaPrincipal.setLayer(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        fundoTelaPrincipal.setLayer(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout fundoTelaPrincipalLayout = new javax.swing.GroupLayout(fundoTelaPrincipal);
        fundoTelaPrincipal.setLayout(fundoTelaPrincipalLayout);
        fundoTelaPrincipalLayout.setHorizontalGroup(
            fundoTelaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fundoTelaPrincipalLayout.createSequentialGroup()
                .addGap(104, 104, 104)
                .addGroup(fundoTelaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(fundoTelaPrincipalLayout.createSequentialGroup()
                        .addGroup(fundoTelaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3))
                        .addGap(141, 141, 141))
                    .addGroup(fundoTelaPrincipalLayout.createSequentialGroup()
                        .addComponent(jLabelFnr)
                        .addGap(18, 18, 18)
                        .addComponent(jLabelLogoMonetae)))
                .addContainerGap(110, Short.MAX_VALUE))
        );
        fundoTelaPrincipalLayout.setVerticalGroup(
            fundoTelaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fundoTelaPrincipalLayout.createSequentialGroup()
                .addGap(153, 153, 153)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addGap(34, 34, 34)
                .addGroup(fundoTelaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fundoTelaPrincipalLayout.createSequentialGroup()
                        .addComponent(jLabelLogoMonetae)
                        .addGap(39, 39, 39))
                    .addComponent(jLabelFnr, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap(159, Short.MAX_VALUE))
        );

        menuInicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/monetae/imagens/icoAtendimento24x24.png"))); // NOI18N
        menuInicio.setMnemonic('A');
        menuInicio.setText("Arquivo");

        subMenuCostumer.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        subMenuCostumer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/monetae/imagens/icoAtendimento24x24.png"))); // NOI18N
        subMenuCostumer.setMnemonic('t');
        subMenuCostumer.setText("Atendimento ao cliente");
        subMenuCostumer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subMenuCostumerActionPerformed(evt);
            }
        });
        menuInicio.add(subMenuCostumer);

        subMenuSair.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        subMenuSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/monetae/imagens/iconBtnOff24x24.png"))); // NOI18N
        subMenuSair.setMnemonic('S');
        subMenuSair.setText("Sair");
        subMenuSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subMenuSairActionPerformed(evt);
            }
        });
        menuInicio.add(subMenuSair);

        menuTelaPrincipal.add(menuInicio);

        menuSettings.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/monetae/imagens/iconSettings24x24.png"))); // NOI18N
        menuSettings.setMnemonic('g');
        menuSettings.setText("Configurações");

        subMenuIdioma.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/monetae/imagens/iconEarth24x24.png"))); // NOI18N
        subMenuIdioma.setText("Idioma");

        subMenuIdiomaBR.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        subMenuIdiomaBR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/monetae/imagens/brazil_flags_24x24.png"))); // NOI18N
        subMenuIdiomaBR.setMnemonic('P');
        subMenuIdiomaBR.setText("Português BR");
        subMenuIdiomaBR.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                subMenuIdiomaBRMouseClicked(evt);
            }
        });
        subMenuIdiomaBR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subMenuIdiomaBRActionPerformed(evt);
            }
        });
        subMenuIdioma.add(subMenuIdiomaBR);

        subMenuIdiomaEN.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        subMenuIdiomaEN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/monetae/imagens/united_states_flags_24x24.png"))); // NOI18N
        subMenuIdiomaEN.setMnemonic('I');
        subMenuIdiomaEN.setText("Inglês");
        subMenuIdiomaEN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subMenuIdiomaENActionPerformed(evt);
            }
        });
        subMenuIdioma.add(subMenuIdiomaEN);

        menuSettings.add(subMenuIdioma);

        menuTelaPrincipal.add(menuSettings);

        menuAbout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/monetae/imagens/IconAbout24x24.png"))); // NOI18N
        menuAbout.setMnemonic('S');
        menuAbout.setText("Sobre");

        submenuSobre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/monetae/imagens/IconAbout24x24.png"))); // NOI18N
        submenuSobre.setMnemonic('P');
        submenuSobre.setText("Sobre o Programa");
        submenuSobre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submenuSobreActionPerformed(evt);
            }
        });
        menuAbout.add(submenuSobre);

        submenuProjeto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/monetae/imagens/iconePdf24x24.png"))); // NOI18N
        submenuProjeto.setText("Definições do Projeto");
        submenuProjeto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submenuProjetoActionPerformed(evt);
            }
        });
        menuAbout.add(submenuProjeto);

        menuTelaPrincipal.add(menuAbout);

        setJMenuBar(menuTelaPrincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fundoTelaPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fundoTelaPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(816, 639));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void subMenuCostumerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subMenuCostumerActionPerformed
        // TODO add your handling code here:
        TelaAtendimento tela = new TelaAtendimento();
        ((BasicInternalFrameUI)tela.getUI()).setNorthPane(null); //retirar o painel superior
        fundoTelaPrincipal.add(tela);
        tela.setVisible(true);
    }//GEN-LAST:event_subMenuCostumerActionPerformed

    private void subMenuIdiomaENActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subMenuIdiomaENActionPerformed
        // TODO add your handling code here:
        Traduzir.traduzir(1);
    }//GEN-LAST:event_subMenuIdiomaENActionPerformed

    private void subMenuIdiomaBRMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_subMenuIdiomaBRMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_subMenuIdiomaBRMouseClicked

    private void subMenuIdiomaBRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subMenuIdiomaBRActionPerformed
        // TODO add your handling code here:
        Traduzir.traduzir(0);
    }//GEN-LAST:event_subMenuIdiomaBRActionPerformed

    private void subMenuSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subMenuSairActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_subMenuSairActionPerformed

    private void submenuSobreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submenuSobreActionPerformed
        // TODO add your handling code here:
        TelaSobre tela = new TelaSobre();
        ((BasicInternalFrameUI)tela.getUI()).setNorthPane(null); //retirar o painel superior
        fundoTelaPrincipal.add(tela);
        tela.setVisible(true);
    }//GEN-LAST:event_submenuSobreActionPerformed

    private void submenuProjetoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submenuProjetoActionPerformed
        try {
            // TODO add your handling code here:
            Desktop.getDesktop().open(new File("projeto.pdf"));
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(this, "Probelma na abertura do arquivo\n"+
                    "Verifique Se o arquivo 'Projeto.pdf' se encontra na raiz do projeto");
        }
    }//GEN-LAST:event_submenuProjetoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane fundoTelaPrincipal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelFnr;
    private javax.swing.JLabel jLabelLogoMonetae;
    public static javax.swing.JMenu menuAbout;
    public static javax.swing.JMenu menuInicio;
    public static javax.swing.JMenu menuSettings;
    private javax.swing.JMenuBar menuTelaPrincipal;
    public static javax.swing.JMenuItem subMenuCostumer;
    public static javax.swing.JMenu subMenuIdioma;
    public static javax.swing.JMenuItem subMenuIdiomaBR;
    public static javax.swing.JMenuItem subMenuIdiomaEN;
    public static javax.swing.JMenuItem subMenuSair;
    public static javax.swing.JMenuItem submenuProjeto;
    public static javax.swing.JMenuItem submenuSobre;
    // End of variables declaration//GEN-END:variables
}
